// eslint-disable-next-line no-unused-vars
const { capitalize } = require('../utilities');

module.exports = {
  getTemplate: (schema, config) => {
    let template = `
    // THIS IS AN AUTOGENERATED FILE
    // DO NOT EDIT
    // IT WILL BE OVERWRITTEN

    const privateMethods = require('../methods/privateMethods.js');

    module.exports = {
    schema: {
    `;

    for (const [modelName, modelValue] of Object.entries(schema)) {
      if (schema.hasOwnProperty(modelName)) {
        // TODO: add more field types here, now it just copies whatever into the fielde
        const modelLength = Object.keys(modelValue).length;
        let count = 0;
        template += `
          ${modelName}: {`;

        for (const [key, value] of Object.entries(modelValue)) {
          template += `
            ${key}: ${value}`;

          count++;
          if (count < modelLength) {
            template += ',';
          }
        }

        template += `
          },
        `;
      }
    }

    template += `
      }
    };

    `;

    return template;
  }
};
